### ISSUE TITLE
Extra powershell commands in Windows

### ISSUE THREAD

**Issue by nuttiplutt** [Les-El/Ollm-Bridge#2]
Hello, your script worked perfectly, but I had some problems running the script in PowerShell initially since it is unsigned. Here is how it was solved with the help of AI, of course:

If you want to allow all scripts, you can use:

```powershell
Set-ExecutionPolicy -ExecutionPolicy Unrestricted
``` 

Run Your Script Again:
Now, try running your script again:
```powershell
 .\Ollm_Bridge_v0.6.ps1
```

Important Note
Changing the execution policy can expose your system to potential security risks. It’s generally recommended to revert to a more restrictive policy after running your script:

```powershell
Set-ExecutionPolicy -ExecutionPolicy Restricted
```

**Comment by Les-El** [comment]
Thanks!
